name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 触发条件：推送以 v 开头的标签时
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest  # 使用 Windows 环境来构建 exe 和 apk
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: 设置 Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'  # 使用稳定版本
        channel: 'stable'
        
    - name: 获取依赖
      run: flutter pub get
      
    - name: 构建 Windows exe
      run: |
        flutter config --enable-windows-desktop
        flutter build windows --release
        
    - name: 构建 Android APK
      run: |
        flutter build apk --release --split-per-abi
        
    - name: 压缩 Windows 构建文件
      run: |
        cd build/windows/x64/runner/Release
        7z a -tzip ../../../../../calculator-windows.zip .
        
    - name: 获取版本号
      id: get_version
      run: |
        if ("${{ github.ref }}" -like "refs/tags/*") {
          $version = "${{ github.ref }}" -replace "refs/tags/", ""
          echo "version=$version" >> $env:GITHUB_OUTPUT
        } else {
          $version = "latest"
          echo "version=$version" >> $env:GITHUB_OUTPUT
        }
      shell: powershell
      
    - name: 创建 Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Calculator ${{ steps.get_version.outputs.version }}
        body: |
          ## 更新内容
          - Windows 可执行文件 (calculator-windows.zip)
          - Android APK 文件 (按架构分离)
          
          ## 下载说明
          - Windows 用户下载 calculator-windows.zip
          - Android 用户根据设备架构下载对应的 APK 文件：
            - arm64-v8a: 适用于大多数现代 Android 设备
            - armeabi-v7a: 适用于较老的 Android 设备
            - x86_64: 适用于 x86 架构的 Android 设备
        draft: false
        prerelease: false
        
    - name: 上传 Windows 文件到 Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./calculator-windows.zip
        asset_name: calculator-windows.zip
        asset_content_type: application/zip
        
    - name: 上传 Android APK (arm64-v8a) 到 Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        asset_name: calculator-arm64-v8a.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: 上传 Android APK (armeabi-v7a) 到 Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
        asset_name: calculator-armeabi-v7a.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: 上传 Android APK (x86_64) 到 Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/app/outputs/flutter-apk/app-x86_64-release.apk
        asset_name: calculator-x86_64.apk
        asset_content_type: application/vnd.android.package-archive